version: "3.8"
services:
  plat-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plat-fe-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URI=https://api.plat.so # 운영 API 주소
    restart: always
