import type ko from "./ko";

const en: typeof ko = {
  chatRoom: {
    closedNotice:
      "This character has been deleted, so you can no longer chat. Your past conversation is still here.",
    handoverPendingNotice: "This character is under operator review. You can keep chatting.",
    generatedNotice: "Replies are generated by AI and may not reflect real people or facts.",
    sidebar: {
      title: "Chat room settings",
      back: "Go back",
      openSettings: "Open chat room settings",
      close: "Close chat room settings",
      backToSettings: "Back to chat room settings",
      ownedNotes: "Owned notes",
      userSettings: "User settings",
      memoryLog: "Memory log",
      chatSettings: "Chat settings",
      memory: "Past conversations",
      pastConversations: "Past conversations",
      memoryDescription:
        "Conversations are summarized automatically so the character can remember longer.",
      memoryPlaceholder:
        "Write what you'd like the character to remember from your conversations so far",
      memorySaveButton: "Save",
      memorySavedToast: "Memory has been saved",
      memoryTurn: "Turn {turn}",
      editMemory: "Edit memory",
      memoryCancelButton: "Cancel",
      memoryEmpty: "No remembered conversations yet",
      persona: "Persona",
      userNote: "User note",
      assetGallery: "Asset gallery",
      assetGalleryEmpty: "No assets yet",
      assetTotal: "Total  {count}",
      suggestedReply: "Suggested replies",
      novelView: "View as novel",
      assetView: "Show assets",
      assetLocked: "Locked asset",
      backToAssetGallery: "Back to asset gallery",
      restartChat: "Restart chat",
      leaveChat: "Leave chat room",
    },
  },
};

export default en;
