export const DUMMY_CHARACTERS = [
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
  {
    id: "398292",
    name: "옆자리 불량학생",
    chatCount: 123,
    dec: "옆자리 불량학생이 매일 학교에서 일어나는 일들을 이야기해주는 채팅입니다.",
    tag: ["학교", "일상", "친구", "친구", "친구", "친구"],
    img: "https://picsum.photos/200/300",
    isPublic: false,
  },
];
